name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version
        required: true
        default: 1.0.0
      snapshotVersion:
        description: Snapshot Version
        required: true
        default: 1.0.0-SNAPSHOT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0

    - name: Set up JDK 13
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 13
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
        architecture: x64
    - name: Set Maven Version
      run: mvn versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
    - name: Publish package
      run: mvn deploy -P release -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Set Chronos Version
      run: echo CHRONOS_VERSION=${{ github.event.inputs.releaseVersion }}  >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    - name: Set Multi-Builder Docker Buildx
      run: docker buildx create --use --name multi-builder --platform linux/arm64,linux/amd64
    - name: Maven Build
      run: mvn clean install -Dmaven.javadoc.skip=false
    - name: Docker Login
      run: docker login ${{secrets.DOCKER_REGISTRY}} -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Push Chronos
      run: |
        cd releng/chronos-platform
        docker build --load -t ghcr.io/codbex/codbex-chronos:${{ env.CHRONOS_VERSION }} .
        docker push ghcr.io/codbex/codbex-chronos:${{ env.CHRONOS_VERSION }}
        cd ../../
    - name: Push Chronos - Keycloack
      run: |
        cd releng/chronos-platform-keycloack
        docker build --load -t ghcr.io/codbex/codbex-chronos-keycloack:${{ env.CHRONOS_VERSION }} .
        docker push ghcr.io/codbex/codbex-chronos-keycloack:${{ env.CHRONOS_VERSION }}
        cd ../../
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ env.CHRONOS_VERSION }}
        name: ${{ env.CHRONOS_VERSION }}
        draft: false
        prerelease: false
        files: |
          LICENSE
        body: |
          ## Codbex Chronos - ${{ env.CHRONOS_VERSION }}

          Timesheets Management Application
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: europe-north1-a

    - name: Update deployment
      run: |
        kubectl -n ${{ secrets.GKE_NAMESPACE }} set image deployment/${{ secrets.GKE_DEPLOY }} dirigible=ghcr.io/codbex/codbex-chronos-keycloack:${{ env.CHRONOS_VERSION }}
