name: Release - Application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/application-release.yaml@main
    with:
      application-name: codbex-aion
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-aion - ${{ github.event.inputs.releaseVersion }}
  
        Timesheets Management Application
  
        ## Deployment
  
        ```
        docker run --name codbex-aion \
        --rm -p 8080:8080 -p 8081:8081 \
        ghcr.io/codbex/codbex-aion:${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - [/services/web/codbex-aion/gen/](http://localhost:8080/services/web/codbex-aion/gen/) - Admin Panel
        - [/services/web/codbex-aion-ext/ui/employee/](http://localhost:8080/services/web/codbex-aion-ext/ui/employee/) - Employee Dashboard
        - [/services/web/codbex-aion-ext/ui/manager/](http://localhost:8080/services/web/codbex-aion-ext/ui/manager/) - Manager Dashboard
    secrets: inherit
